payments/docs/views.py
from flask import (
    render_template,
)

from ..helpers import Blueprint


bp = Blueprint('docs', __name__)
bp.nav('main_nav', [
    ('index', 'Documentation'),
])


@bp.route('/')
def index():
    return render_template('docs/documentation.html')

payments/templates/payments/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='payments.png') }}">

	<title>{% block title %}{% endblock %}Payments</title>

	{% if use_cdn %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	{% else %}
		<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
	{% endif %}
	<link rel="stylesheet" href="{{ url_for('static', filename='icomoon/style.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	<script src="{{ url_for('static', filename='iframe.js') }}"></script>

	{% block head %}{% endblock %}
</head>
<body>

{% set active_page = active_page|default('unknown') -%}
{% set no_nav = no_nav|default(False) -%}

	{% if not no_nav %}
		<nav id="page-nav" class="navbar navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="{{ url_for('docs.index') }}">
				<img src="{{ url_for('static', filename='payments.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
				Payments
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					{% for name, title in navs.main_nav %}
						<li class="nav-item {% if name == active_page %}active{% endif %}">
							<a class="nav-link" href="{{ url_for(name) }}">{{ title }}</a>
						</li>
					{% endfor %}
					<li class="nav-item {% if 'payments.forget_me' == active_page %}active{% endif %}">
						{% if session %}
							<a class="nav-link" href="{{ url_for('payments.forget_me') }}">Forget me!</a>
						{% else %}
							<a class="nav-link" href="{{ url_for('payments.forget_me') }}">Privacy</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</nav>
	{% endif %}

	<div class="container">
		{% block content %}{% endblock %}
	</div>

	<footer id="page-footer" class="bg-light">
		<div class="text-center">
			© 2010
			<a href="https://github.com/Aalto-LeTech/simple-payments/">Simple Payments</a>
			v{{ version }}
			- For purely educational purposes!
		</div>
	</footer>
</body>
</html>

payments/templates/payments/forget_me.html
{% extends 'payments/base.html' %}
{% set active_page = 'payments.forget_me' %}

{% from 'history/_history.html' import reset_button %}

{% block title %}{% if session %}Forget me!{% else %}Privacy{% endif %} | {{ super() }}{% endblock %}

{% block head %}
	<script src="{{ url_for('static', filename='are_you_sure.js') }}"></script>
{% endblock%}

{% block content %}
	<div class="row mt-4 mb-4">
		<div class="col-12">
			<h2>{% if session %}Forget me!{% else %}Privacy{% endif %}</h2>

			<p class="alert alert-info">
				This site does not store any information about you in the server, but some parts of the site can use cookies to provide extra features to you.<br>
				Features are enabled by selecting respective checkboxes.
			</p>

			{% if session %}
				<p class="alert alert-warning">
					There is data in your session cookie. In total of {{ session|length }} entries.
				</p>
				<p>{{ reset_button('clear_session', "Remove session cookie and all information in it!", 'danger', 'btn-lg') }}</p>
			{% else %}
				<p class="alert alert-success">
					Currently, there is no information stored in the session and thus there is no cookie in your device.
				</p>
			{% endif %}
		</div>
	</div>
{% endblock %}