payments/bank/models.py
from time import time

from ..models import (
    DateMixin,
    SellerMixin,
    SimpleModel,
    SessionModel
)
from ..utils import (
    create_ref,
    jwt_decode,
    jwt_encode,
)


class PaymentRequest(SellerMixin, SimpleModel):
    FIELDS = ('sid', 'pid', 'amount', 'success_url', 'cancel_url', 'error_url', 'message')

    @classmethod
    def from_jwt(cls, encoded):
        ok, data_or_error = jwt_decode(encoded)
        if ok:
            data_or_error = cls(**data_or_error)
        return ok, data_or_error

    def to_jwt(self, expire_in_sec=None):
        return jwt_encode(self.to_dict(), expire_in_sec=expire_in_sec)

    def to_record(self, result):
        return PaymentRecord(
            sid=self.sid,
            pid=self.pid,
            amount=self.amount,
            date=int(time()),
            result=result,
        )


class PaymentRecord(SellerMixin, DateMixin, SessionModel):
    FIELDS = ('sid', 'pid', 'amount', 'ref', 'date', 'result')
    KEY_FIELDS = ('sid', 'pid')
    KEY_PREFIX = 'payment'

    def __init__(self, **kwargs):
        ref = kwargs.pop('ref', None)
        super().__init__(**kwargs)
        if not ref and self.sid and self.pid:
            ref = create_ref(self.sid, self.pid)
        self.ref = ref

payments/bank/forms.py
from hmac import compare_digest
from wtforms import (
    DecimalField,
    StringField,
    validators,
)

from ..forms import Form
from ..utils import get_checksum
from .models import PaymentRecord, PaymentRequest


sid_field = StringField('Seller ID', [
    validators.required(),
    validators.Length(max=255),
    validators.Regexp('^[a-zA-Z0-9_-]+={0,2}$')])
pid_field = StringField('Payment ID', [validators.required(), validators.Length(max=64)])
checksum_field = StringField('Checksum', [validators.required()])


class PaymentRequestForm(Form):
    sid = sid_field
    pid = pid_field
    amount = DecimalField('Amount', [validators.required(), validators.NumberRange(min=0)], places=2)
    checksum = checksum_field
    success_url = StringField('Success URL', [validators.required(), validators.URL(require_tld=False)])
    cancel_url = StringField('Cancel URL', [validators.required(), validators.URL(require_tld=False)])
    error_url = StringField('Error URL', [validators.required(), validators.URL(require_tld=False)])

    def validate(self):
        if not super().validate():
            return False
        # Validate checksum
        test = get_checksum(self, ('pid', 'sid', 'amount'), getter=lambda o, k: getattr(o, k).raw_data[0])
        if not compare_digest(test, self.checksum.data):
            # Check https://docs.python.org/3/library/hmac.html#hmac.compare_digest for reason why this is used in place of a != b
            self.checksum.errors.append("The checksum does not match the data")
            return False
        # Validate unique pid
        old_payment = PaymentRecord.from_session(self.sid.data, self.pid.data)
        if old_payment:
            self.pid.errors.append(
                "A payment with this pid has already been processed. "
                "Time: {}, Result: {}, Ref: {}".format(
                    old_payment.datestr, old_payment.result, old_payment.ref))
            self._old_payment = old_payment
            return False
        return True

    def get_payment(self):
        obj = PaymentRequest()
        self.populate_obj(obj)
        obj.old = self._old_payment if hasattr(self, '_old_payment') else None
        obj.message = self.errors_as_string
        return obj

payments/bank/__init__.py
from .views import bp

payments/bank/views.py
from urllib.parse import parse_qsl, urlencode, urlsplit
from flask import (
    abort,
    current_app as app,
    redirect,
    render_template,
    request,
    session,
)

from ..helpers import Blueprint
from ..utils import get_checksum
from .forms import PaymentRequestForm
from .models import PaymentRecord, PaymentRequest


ACTIONS = {'success', 'cancel', 'error'}

bp = Blueprint('bank', __name__)


@bp.route('/pay', methods=['GET', 'POST'])
#@csrf_exempt
def pay():
    data = request.args if request.method == 'GET' else request.form
    form = PaymentRequestForm(data)
    form.validate()
    payment = form.get_payment()
    if 'history' in app.config['apps']:
        PaymentRecord.remove_old_and_limit()
        payment_history = PaymentRecord.all_from_session(payment.sid)[:10] if payment.sid else []
        cookies_ok = session.get('cookies-ok', False)
    else:
        PaymentRecord.clear_all_from_session()
        session.pop('cookies-ok', None)
        payment_history = []
        cookies_ok = None
    return render_template('bank/pay.html',
        payment=payment,
        payment_data=payment.to_jwt(expire_in_sec=300), # 5min
        payment_history=payment_history,
        cookies_ok=cookies_ok,
    )


@bp.route('/process', methods=['POST'])
def process():
    # Validate call
    action = request.form.get('action', '')
    if action not in ACTIONS:
        abort(404)

    # Resolve and validate payment request
    payment_data = request.form.get('payment', '')
    ok, payment = PaymentRequest.from_jwt(payment_data)
    if not ok:
        return str(payment), 400

    record = payment.to_record(action)

    # Check for old
    old_record = PaymentRecord.from_session(payment.sid, payment.pid)
    if old_record and old_record.result:
        if action != 'error':
            return "Payment already done", 400
        record = old_record
        record.result = 'error'

    # Cookies
    if not session.get('cookies-ok', False) and request.form.get('cookies_ok', 'no') == 'yes' and 'history' in app.config['apps']:
        session['cookies-ok'] = True

    # Save record
    if not old_record and session.get('cookies-ok', False):
        record.save_to_session()

    # Do redirect
    url = urlsplit(payment[action + '_url'])
    query = [(k, v) for k, v in parse_qsl(url.query) if k not in {'pid', 'ref', 'result', 'checksum'}]
    query += get_checksum(record, ('pid', 'ref', 'result'), with_params=True)
    if payment.message:
        query += [('message', payment.message)]
    redirect_url = url._replace(query=urlencode(query), fragment='').geturl()
    return redirect(redirect_url)

payments/history/views.py
from flask import (
    render_template,
    request,
    session,
)

from ..bank.models import PaymentRecord
from ..helpers import Blueprint


bp = Blueprint('history', __name__, url_prefix='/history')
bp.nav('main_nav', [
    ('history', 'Payment History'),
])


@bp.route('', methods=['GET', 'POST'])
def history():
    history = PaymentRecord.all_from_session()
    if request.method == 'POST':
        if request.form.get('clear_cookie', 'no') == 'yes':
            if 'cookies-ok' in session:
                del session['cookies-ok']
            PaymentRecord.clear_all_from_session()
        elif request.form.get('do_reset', 'no') == 'yes':
            PaymentRecord.clear_all_from_session()
        else:
            return "Invalid post action", 400
        history = []
    return render_template('history/history.html',
        history=history,
        cookies_ok=session.get('cookies-ok', False),
    )

payments/templates/bank/pay.html
{% extends 'payments/base.html' %}
{% from '_form.html' import render_field %}

{% block title %}A Payment Request | {{ super() }}{% endblock %}

{% block head %}
	<link rel="stylesheet" href="{{ url_for('static', filename='pay.css') }}">
	<script src="{{ url_for('static', filename='pay.js') }}"></script>
{% endblock %}

{% macro post_action(action, message, color='primary') %}
	<form method="POST" action="{{ url_for('bank.process') }}">
		<input type="hidden" name="action" value="{{ action }}">
		<input type="hidden" name="cookies_ok" value="{{ 'yes' if cookies_ok else 'no' }}">
		<input type="hidden" name="payment" value="{{ payment_data }}">
		<button type="submit" class="btn btn-{{ color }} btn-lg btn-block">{{ message }}</button>
	</form>
{% endmacro %}

{% block content %}
	<h1 class="mt-4">A Payment request</h1>

	<div class="row">
		<div class="col-12">
			<table class="table">
				<tr>
					<th>Seller</th>
					<td>{{ payment.seller }}</td>
				</tr>
				<tr>
					<th>Payment ID</th>
					<td>{{ payment.pid }}</td>
				<tr>
					<th>Amount</th>
					<td>{{ payment.amount }}</td>
				</tr>
			</table>
		</div>
	</div>

	{% if cookies_ok is not none %}
		<div class="row">
			<div class="col-12 decorated-checkbox">
				<input id="use-cookies" type="checkbox" value="yes" {% if cookies_ok %}checked disabled{% endif %}>
				<label for="use-cookies">
					Use cookies to keep a record of a payment history and to fail used payment ids.<br>
					All data and this option can be removed on the history page or via browser settings.
				</label>
			</div>
		</div>
	{% endif %}

	{% if payment.message %}
		<div class="row">
			<div class="col-12">
				<div class="alert alert-warning" role="alert">
					<h4 class="alert-heading">The payment request validation errors</h4>
					<pre>{{ payment.message }}</pre>
				</div>
			</div>
		</div>
	{% endif %}

	<div class="row" id="buttons-row">
		{% if payment.message %}
			<div class="col-6 press-automatically" data-expire-in="240">
				{{ post_action('error', 'Return with error', 'danger') }}
			</div>
		{% else %}
			<div class="col-6">
				{{ post_action('success', 'Accept payment', 'success') }}
			</div>
			<div class="col-6 press-automatically" data-expire-in="240">
				{{ post_action('cancel', 'Cancel payment', 'warning') }}
			</div>
		{% endif %}
	</div>

	{% if payment_history or cookies_ok %}
		<div class="row mt-4">
			<div class="col-12 card border-info">
				<div class="card-body">
					<h3 class="card-title">Latest payment history for this seller</h3>
					{% if payment_history %}
						<table class="table table-sm card-text">
							<thead class="thead-light">
								<tr>
									<th>Date</th>
									<th>Amount</th>
									<th>Result</th>
									<th>Payment ID</th>
									<th>Reference ID</th>
								</tr>
							</thead>
							<tbody>
								{% for p in payment_history %}
									<tr {% if p.ref == payment.old.ref %}class="table-info"{% endif %}>
										<td>{{ p.datestr }}</td>
										<td>{{ p.amount }}</td>
										<td><small class="badge badge-{{ p.result|result_badge_color }}">{{ p.result }}</small></td>
										<td>{{ p.pid }}</td>
										<td>{{ p.ref }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					{% else%}
						<p>No previous payments yet.</p>
					{% endif %}
					<a href="{{ url_for('history.history') }}" target="_blank" class="btn btn-info">See your full payment history</a>
				</div>
			</div>
		</div>
	{% endif %}

{% endblock %}