payments/tester/models.py
from ..models import (
    DateMixin,
    SellerMixin,
    SessionModel,
)


class TestRequest(SellerMixin, DateMixin, SessionModel):
    FIELDS = ('sid', 'pid', 'amount', 'ref', 'result', 'date', 'token')
    KEY_FIELDS = ('pid',)
    KEY_PREFIX = 'testreq'

payments/tester/forms.py
from collections import OrderedDict
from decimal import Decimal
from wtforms import (
    BooleanField,
    DecimalField,
    StringField,
    validators,
)

from ..forms import Form
from ..utils import get_checksum
from ..bank.forms import (
    sid_field,
    pid_field,
    checksum_field,
    PaymentRequestForm,
)


class TestPaymentRequestForm(Form):
    sid = sid_field
    token = StringField('Secret Token', [validators.required(), validators.Length(max=64)])
    amount = DecimalField('Amount', [validators.required()], places=2)
    pid = pid_field
    service = StringField('Service URL', [validators.required(), validators.URL(require_tld=False)])
    disable_iframe = BooleanField("Disable iframe and always open in a new window")
    use_cookies = BooleanField("Save the request info in a cookie for callback validation and history")
    skip_confirm = BooleanField('Skip a confirm page and directly forward to the payment service')

    def validate_amount(self, field):
        field.data = field.data.quantize(Decimal('0.01'))

    def get_post_data(self, **extra):
        data = OrderedDict()
        for field in self:
            data[field.short_name] = str(field.data)
        data['checksum'] = get_checksum(data, ('pid', 'sid', 'amount', 'token'), token=False)
        data.update(extra)
        drop = set(data.keys()) - set(f.name for f in PaymentRequestForm())
        for key in drop:
            del data[key]
        return data


class TestPaymentResponseForm(Form):
    pid = pid_field
    ref = StringField('Reference ID', [validators.required(), validators.Length(max=64)])
    result = StringField('Result', [
        validators.Length(max=64),
        validators.AnyOf(('success', 'cancel', 'error')),
        validators.Optional(),
    ])
    checksum = checksum_field
    message = StringField('Error message',  [validators.Optional()])

    def validate(self):
        if not super().validate():
            return False
        # Validate checksum
        if hasattr(self, '_token'):
            token = self._token
            fields = ('pid', 'ref', 'result') if self.result.data else ('pid', 'ref')
            test = get_checksum(self, fields, getter=lambda o, k: getattr(o, k).raw_data[0], token=token)
            if test != self.checksum.data:
                self.checksum.errors.append("The checksum does not match the data")
                return False
        # Validate unique pid
        if hasattr(self, '_old'):
            old = self._old
            if old and old['result'] is not None:
                self.pid.errors.append(
                    "A payment with this pid has already been processed. "
                    "Time: {date}, Result: {result}, Ref: {ref}".format(**old))
                return False
        return True

payments/creator/views.py
from flask import (
    current_app as app,
    redirect,
    render_template,
    request,
    url_for,
)

from ..helpers import Blueprint
from ..utils import create_seller_id, get_token
from .forms import KeyRequestForm


bp = Blueprint('creator', __name__, url_prefix='/request-sid')
bp.nav('main_nav', [
    ('getsid', 'Get Seller ID'),
])


@bp.route('', methods=['GET', 'POST'])
def getsid():
    form = KeyRequestForm(request.form)
    if request.method == 'POST' and form.validate():
        name = form.seller.data
        sid = create_seller_id(name)
        token = get_token(sid)
        # FIXME: select between redirect and result
        if 'tester' in app.config['apps']:
            return redirect(url_for('tester.index',
                sid=sid.decode('ascii'),
                token=token,
            ))
        return render_template('creator/key_result.html',
            name=name,
            sid=sid.decode('ascii'),
            token=token,
        )
    return render_template('creator/key_form.html', form=form)

payments/history/__init__.py
from .views import bp

payments/history/views.py
from flask import (
    render_template,
    request,
    session,
)

from ..bank.models import PaymentRecord
from ..helpers import Blueprint


bp = Blueprint('history', __name__, url_prefix='/history')
bp.nav('main_nav', [
    ('history', 'Payment History'),
])


@bp.route('', methods=['GET', 'POST'])
def history():
    history = PaymentRecord.all_from_session()
    if request.method == 'POST':
        if request.form.get('clear_cookie', 'no') == 'yes':
            if 'cookies-ok' in session:
                del session['cookies-ok']
            PaymentRecord.clear_all_from_session()
        elif request.form.get('do_reset', 'no') == 'yes':
            PaymentRecord.clear_all_from_session()
        else:
            return "Invalid post action", 400
        history = []
    return render_template('history/history.html',
        history=history,
        cookies_ok=session.get('cookies-ok', False),
    )

payments/tester/__init__.py
from .views import bp

payments/tester/views.py
from flask import (
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from ..helpers import Blueprint
from ..utils import (
    geturl_with_updated_data,
    geturl_with_updated_query,
    seller_name_from_id,
)
from .models import TestRequest
from .forms import (
    TestPaymentRequestForm,
    TestPaymentResponseForm,
)


bp = Blueprint('tester', __name__, url_prefix='/test')
bp.nav('main_nav', [
    ('index', 'Test service'),
    ('history', 'Test history'),
])

test_session_keys = {
    'disable_iframe': 'test-force-iframe',
    'use_cookies': 'test-cookies-ok',
    'skip_confirm': 'test-skip-confirm',
}


@bp.route('/', methods=['GET'])
def index():
    data = {
        'sid': request.args.get('sid', ''),
        'token': request.args.get('token', ''),
        'service': url_for('bank.pay', _external=True),
    }
    for fn, sk in test_session_keys.items():
        data[fn] = session.get(sk, False)
    form = TestPaymentRequestForm(data=data)

    return render_template('tester/index.html',
        form=form,
        seller=seller_name_from_id(form.sid.data),
    )


@bp.route('/post', methods=['POST'])
def post():
    form = TestPaymentRequestForm(request.form)

    if form.validate():
        data = form.get_post_data(
            success_url = url_for('tester.result', result='success', _external=True),
            cancel_url = url_for('tester.result', result='cancel', _external=True),
            error_url = url_for('tester.result', result='error', _external=True),
        )
        if form.use_cookies.data:
            TestRequest.remove_old_and_limit()
            record = TestRequest()
            form.populate_obj(record)
            record.save_to_session()
            for fn, sk in test_session_keys.items():
                session[sk] = form[fn].data
        else:
            for sk in test_session_keys.values():
                if sk in session:
                    del session[sk]
        if form.skip_confirm.data:
            url = geturl_with_updated_query(form.service.data, data)
            return redirect(url, code=302)
        url, data = geturl_with_updated_data(form.service.data, data)
        return render_template('tester/post.html',
            data=data,
            service=url,
        )
    return render_template('tester/error.html', form=form), 400


@bp.route('/callback/<result>')
def result(result):
    form = TestPaymentResponseForm(request.args)
    if form.result.data:
        result = form.result.data
    record = TestRequest.from_session(form.pid.data) if form.pid.data else None
    if record:
        form._token = record.token
        form._old = record.to_dict()
        form._old['date'] = record.datestr
        record.result = result
        record.ref = form.ref.data
        record.date = None # Update date
        record.save_to_session()
        payment_history = [r for r in TestRequest.all_from_session() if r.sid == record.sid][:10]
    else:
        payment_history = []
    return render_template('tester/result.html',
        form=form,
        record=record,
        result=result,
        payment_history=payment_history,
        cookies_ok=session.get('test-cookies-ok', False),
    )


@bp.route('/history', methods=['GET', 'POST'])
def history():
    history = TestRequest.all_from_session()
    if request.method == 'POST':
        if request.form.get('clear_cookie', 'no') == 'yes':
            for sk in test_session_keys.values():
                if sk in session:
                    del session[sk]
            TestRequest.clear_all_from_session()
        elif request.form.get('do_reset', 'no') == 'yes':
            TestRequest.clear_all_from_session()
        else:
            return "Invalid post action", 400
        history = []
    return render_template('tester/history.html',
        history=history,
        cookies_ok=session.get('test-cookies-ok', False),
    )

payments/templates/tester/error.html
{% extends 'payments/base.html' %}
{% set no_nav = True %}

{% block title %}Create a test payment | {{ super() }}{% endblock %}

{% block content %}
	<div class="row mt-4">
		<div class="col-12 alert alert-warning" role="alert">
			<h4 class="alert-heading">Validation errors in the form</h4>
			<dl>
				{% for field, errors in form.errors.items() %}
					<dt>{{ field }}</dt>
					<dd><ul>
						{% for error in errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</ul></dd>
				{% endfor %}
			</dl>
		</div>
	</div>
{% endblock %}

payments/templates/tester/history.html
{% extends 'payments/base.html' %}
{% set active_page = 'tester.history' %}

{% from 'history/_history.html' import payment_item, reset_button %}

{% block title %}Test Seller History | {{ super() }}{% endblock %}

{% block head %}
	<script src="{{ url_for('static', filename='are_you_sure.js') }}"></script>
{% endblock%}

{% block content %}
	<div class="row mt-4 mb-4">
		<div class="col-12">
			<div class="d-flex justify-content-between">
				<h2>Payment request history for test service</h2>
				{% if history %}
					{{ reset_button() }}
				{% endif %}
			</div>

			{% if cookies_ok %}
				<div class="alert alert-info d-flex justify-content-between">
					<span>You have enabled cookies for test site</span>
					{{ reset_button('clear_cookie', "Clear test site cookie and all history", 'info', 'btn-sm') }}
				</div>
			{% endif %}

			<div class="list-group">
				{% for payment in history %}
					{{ payment_item(payment) }}
				{% else %}
					<p class="alert alert-info">No recorded payment requests yet</p>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

payments/templates/tester/index.html
{% extends 'payments/base.html' %}
{% set active_page = 'tester.index' %}

{% from '_bootstrap_form.html' import render_field %}

{% block title %}Create a test payment | {{ super() }}{% endblock %}

{% block head %}
	<script src="{{ url_for('static', filename='tester.js') }}"></script>
{% endblock%}

{% block content %}
	<div class="row mt-4 mb-4">
		<div class="col-12">
			<form id="request-form" method="POST" target="request-frame" action="{{ url_for('tester.post') }}">
				<div class="form-row">
					<div class="col-4">
						<div class="form-group">
							<label for="staticSeller">Seller</label>
							<div class="input-group">
								<input type="text" readonly class="form-control" id="staticSller" value="{{ seller }}">
								{% if 'creator' in apps %}
									<div class="input-group-append">
										<a class="btn btn-outline-secondary" href="{{ url_for('creator.getsid') }}">New</a>
									</div>
								{% endif %}
							</div>
						</div>
						{{ render_field(form.sid) }}
						{{ render_field(form.token) }}
					</div>
					<div class="col-4">
						{{ render_field(form.service) }}
						{{ render_field(form.pid) }}
						{{ render_field(form.amount) }}
					</div>
					<div class="col-4 align-self-end">
						{{ render_field(form.disable_iframe) }}
						{{ render_field(form.use_cookies) }}
						{{ render_field(form.skip_confirm) }}
						<button type="submit" class="btn btn-primary btn-lg btn-block">Create a request</button>
					</div>
				</div>
			</form>
		</div>
	</div>

	<div class="row">
		<div class="col-12">
			<iframe id="request-frame" name="request-frame" src="about:blank" height="800" style="width: 100%;"></iframe>
			<p id="request-notice" style="display: none;" class="alert alert-info">The request is will open in a new window.</p>
		</div>
	</div>
{% endblock %}

payments/templates/tester/post.html
{% extends 'payments/base.html' %}
{% from '_form.html' import render_form_fields %}

{% block title %}Send a test payment | {{ super() }}{% endblock %}

{% block content %}
	<div class="row mt-3 mb-4">
		<div class="col-12">
			<div class="card border-primary">
				<div class="card-header">A payment request</div>
				<div class="card-body">
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon3">POST</span>
						</div>
						<input class="form-control mr-sm-2 " type="url" aria-label="url" value="{{ service }}" readonly="readonly">
					</div>
					<table class="table">
						{% for name, value in data.items() %}
							<tr>
								<th>{{ name }}</th>
								<td>{{ value }}</td>
							</tr>
						{% endfor %}
					</table>
					<form method="POST" action="{{ service }}">
						{% for name, value in data.items() %}
							<input type="hidden" name="{{ name }}" value="{{ value }}">
						{% endfor %}
						<button type="submit" class="btn btn-primary btn-lg btn-block">Send</button>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

payments/templates/tester/result.html
{% extends 'payments/base.html' %}
{% from '_form.html' import render_form_fields %}

{% block title %}A test payment result | {{ super() }}{% endblock %}

{% block content %}
	<div class="row mt-3 mb-4">
		<div class="col-12">
			<h1>
				A test payment result
				<span class="badge badge-{{ result | result_badge_color }}">{{ result }}</span>
			</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-12">
			<table class="table">
				{% if record %}
					<tr>
						<th>Receiver</th>
						<td>{{ record.seller }}</td>
					</tr>
					<tr>
						<th>Amount</th>
						<td>{{ record.amount }} ¤</td>
					</tr>
				{% endif %}
				{% for field in (form.pid, form.ref) %}
					<tr>
						<th>{{ field.label.text }}</th>
						<td>{{ field.data }}</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>

	{% if not form.validate() %}
		<div class="row">
			<div class="col-12 alert alert-warning" role="alert">
				<h4 class="alert-heading">There are validation errors in payment response</h4>
				<dl>
					{% for field, errors in form.errors.items() %}
						<dt>{{ field }}</dt>
						<dd><ul>
							{% for error in errors %}
								<li>{{ error }}</li>
							{% endfor %}
						</ul></dd>
					{% endfor %}
				</dl>
			</div>
		</div>
	{% endif %}

	{% if form.message.data %}
		<div class="row">
			<div class="col-12 alert alert-warning" role="alert">
				<h4 class="alert-heading">Error message from the payment service</h4>
				<pre>{{ form.message.data }}</pre>
			</div>
		</div>
	{% endif %}

	{% if payment_history or cookies_ok %}
		<div class="row mt-4">
			<div class="col-12 card border-info">
				<div class="card-body">
					<h3 class="card-title">Latest payment request history for this seller</h3>
					{% if payment_history %}
						<table class="table table-sm card-text">
							<thead class="thead-light">
								<tr>
									<th>Date</th>
									<th>Amount</th>
									<th>Result</th>
									<th>Payment ID</th>
									<th>Reference ID</th>
								</tr>
							</thead>
							<tbody>
								{% for p in payment_history %}
									<tr>
										<td>{{ p.datestr }}</td>
										<td>{{ p.amount }}</td>
										<td><small class="badge badge-{{ p.result|result_badge_color }}">{{ p.result }}</small></td>
										<td>{{ p.pid }}</td>
										<td>{{ p.ref }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					{% endif %}
					<a href="{{ url_for('tester.history') }}" target="_blank" class="btn btn-info">See your full payment request history</a>
				</div>
			</div>
		</div>
	{% endif %}
{% endblock %}